kind: Service
apiVersion: v1
metadata:
  name:  mysql
spec:
  selector:
    app:  mysql
  type:  NodePort
  ports:
  - name:  tcp
    port:  3306
    targetPort:  3306 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: my_app  
        ports:
        - containerPort: 3306
          name: mysql
